import type { EmitOptions, ExtractedTokens, ThemeToken, TokenValue } from "./types.ts";

type Jsonish = TokenValue | boolean | Jsonish[] | { [key: string]: Jsonish };

const IDENT_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function quoteKey(key: string): string {
  return IDENT_RE.test(key) ? key : `'${key.replace(/'/g, "\\'")}'`;
}

function quoteString(value: string): string {
  return `'${value.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\n/g, "\\n")}'`;
}

function serialize(value: Jsonish, indent: number): string {
  const pad = "  ".repeat(indent);
  const padInner = "  ".repeat(indent + 1);
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (typeof value === "string") return quoteString(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value.map((v) => `${padInner}${serialize(v, indent + 1)}`);
    return `[\n${items.join(",\n")},\n${pad}]`;
  }
  const keys = Object.keys(value);
  if (keys.length === 0) return "{}";
  const entries = keys.map(
    (k) => `${padInner}${quoteKey(k)}: ${serialize(value[k] as Jsonish, indent + 1)}`,
  );
  return `{\n${entries.join(",\n")},\n${pad}}`;
}

function camelCase(name: string): string {
  return name.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

function pascalCase(name: string): string {
  return name
    .split("-")
    .map((p) => (p ? p[0]!.toUpperCase() + p.slice(1) : ""))
    .join("");
}

function tokenValue(token: ThemeToken): Jsonish {
  if (token.modifiers) {
    const obj: { [key: string]: Jsonish } = { value: token.light };
    for (const [name, mod] of Object.entries(token.modifiers)) {
      obj[camelCase(name)] = mod.light;
    }
    return obj;
  }
  if (token.light !== token.dark) return { light: token.light, dark: token.dark };
  return token.light;
}

const DEFAULT_HEADER =
  "// AUTO-GENERATED by tailwind-token-extractor. DO NOT EDIT BY HAND.\n" +
  "// Re-run the extractor to update.";

/**
 * Render an {@link ExtractedTokens} object into a self-contained, typed
 * TypeScript module string.
 */
export function emitTypeScript(tokens: ExtractedTokens, options: EmitOptions = {}): string {
  const { header = DEFAULT_HEADER, asConst = true } = options;

  // Build a plain object mirroring the desired literal, then serialize it.
  const themeObj: { [ns: string]: Jsonish } = {};
  const objectNamespaces: string[] = [];
  for (const ns of Object.keys(tokens.theme).sort()) {
    const list = tokens.theme[ns]!;
    const scalar = list.find((t) => t.key === "");
    if (scalar && list.length === 1) {
      themeObj[ns] = tokenValue(scalar);
      continue;
    }
    const group: { [key: string]: Jsonish } = {};
    for (const token of list) {
      group[token.key || "DEFAULT"] = tokenValue(token);
    }
    themeObj[ns] = group;
    objectNamespaces.push(ns);
  }

  const varsObj: { [name: string]: Jsonish } = {};
  for (const v of tokens.vars) {
    varsObj[v.name] = v.light !== v.dark ? { light: v.light, dark: v.dark } : v.light;
  }

  // Symbolic refs: the immediate `var()` target per mode for vars defined as
  // `var(--x)`. Always rendered as a `{ light, dark }` mapping (never collapsed
  // to a scalar) since the value IS the light/dark relationship. A var that
  // references another var in only one mode is skipped — a ref needs both sides.
  const refsObj: { [name: string]: Jsonish } = {};
  for (const v of tokens.vars) {
    if (!v.ref || v.ref.light === null || v.ref.dark === null) continue;
    refsObj[v.name] = { light: v.ref.light, dark: v.ref.dark };
  }

  const metaObj: Jsonish = {
    source: tokens.meta.source,
    tailwindVersion: tokens.meta.tailwindVersion ?? "unknown",
    unresolved: tokens.meta.unresolved,
  };

  const suffix = asConst ? " as const" : "";
  const lines: string[] = [header, ""];

  lines.push(
    `export const tokens = ${serialize({ theme: themeObj, vars: varsObj, refs: refsObj }, 0)}${suffix};`,
  );
  lines.push("");
  lines.push(`export const meta = ${serialize(metaObj, 0)}${suffix};`);
  lines.push("");

  // Derived key-union types for autocomplete.
  lines.push("export type ThemeNamespace = keyof typeof tokens.theme;");
  lines.push("export type VarName = keyof typeof tokens.vars;");
  lines.push("export type RefName = keyof typeof tokens.refs;");
  for (const ns of objectNamespaces) {
    const typeName = `${pascalCase(ns)}Token`;
    // Skip namespaces that don't yield a valid TS identifier (e.g. starts with a digit).
    if (!IDENT_RE.test(typeName)) continue;
    const access = IDENT_RE.test(ns) ? `.${ns}` : `[${quoteString(ns)}]`;
    lines.push(`export type ${typeName} = keyof typeof tokens.theme${access};`);
  }
  lines.push("");

  return lines.join("\n");
}
